name: lucid CI

on:
  workflow_dispatch:
  # push:
  #   branches: [main]
  #   paths:
  #     - "lucid/**"
  #     - "test/**"
  # pull_request:
  #   branches: [main]
  #   paths:
  #     - "lucid/**"
  #     - "test/**"

env:
  LUCID_FLAGS: --enable_gurobi_build=False --enable_matplotlib_build=False

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/bazel-cache

      - name: Build
        run: bazel build ${{ env.LUCID_FLAGS }} //lucid

  lint:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs: build

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/bazel-cache

      - name: Lint
        run: bazel test --build_tests_only ${{ env.LUCID_FLAGS }} //lucid/...

  unit-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    needs: build
    if: false # Temporarily disabled due to performace

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/bazel-cache

      - name: Test
        run: bazel test ${{ env.LUCID_FLAGS }} //tests/unit/...

  integration-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    needs: build
    if: false # Temporarily disabled due to faulty integration

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/bazel-cache

      - name: Test
        run: bazel test ${{ env.LUCID_FLAGS }} //tests/integration/...

  dwyu:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs: build

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/bazel-cache

      - name: Test
        run: bazel build ${{ env.LUCID_FLAGS }} --config=dwyu //lucid
