name: lucid CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "lucid/**"
      - "test/**"
  pull_request:
    branches: [ main ]
    paths:
      - "lucid/**"
      - "test/**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Cache Bazel
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bazel
            /private/var/tmp/_bazel_*
            ~/_bazel_*
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'MODULE.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-

      - name: Build
        run: bazel build //lucid --enable_gurobi_build=False

  # lint:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os: [ubuntu-latest, macos-latest, windows-latest]
  #   runs-on: ${{ matrix.os }}
  #   needs: build

  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.10"

  #     - name: Cache Bazel
  #       uses: actions/cache@v4
  #       with:
  #         path: |
  #           ~/.cache/bazel
  #           /private/var/tmp/_bazel_*
  #           ~/_bazel_*
  #         key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'MODULE.bazel') }}
  #         restore-keys: |
  #           ${{ runner.os }}-bazel-

  #     - name: Lint
  #       run: bazel test //lucid/...

  unit-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Cache Bazel
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bazel
            /private/var/tmp/_bazel_*
            ~/_bazel_*
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'MODULE.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-

      - name: Test
        run: bazel test //tests/unit/... --enable_gurobi_build=False

  integration-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Cache Bazel
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bazel
            /private/var/tmp/_bazel_*
            ~/_bazel_*
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'MODULE.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-

      - name: Test
        run: bazel test //tests/integration/... --enable_gurobi_build=False

  dwyu:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Cache Bazel
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bazel
            /private/var/tmp/_bazel_*
            ~/_bazel_*
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'MODULE.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-

      - name: Test
        run: bazel build //lucid --enable_gurobi_build=False --config=dwyu
