name: pylucid CI

on:
  workflow_dispatch:
  # push:
  #   branches: [main]
  #   paths:
  #     - "lucid/**"
  #     - "bindings/pylucid/**"
  #     - "test/**"
  # pull_request:
  #   branches: [main]
  #   paths:
  #     - "lucid/**"
  #     - "bindings/pylucid/**"
  #     - "test/**"

env:
  LUCID_FLAGS: --enable_gurobi_build=False --enable_matplotlib_build=False

jobs:
  test:
    runs-on: ${{ matrix.os }}
    if: false # TODO: enable this again
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python_version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/bazel-cache
      - uses: ./.github/actions/frontend-setup
        if: matrix.os == 'windows-latest'
      - name: Install openmp on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install llvm libomp
          export CC=/usr/local/opt/llvm/bin/clang
          export CXX=/usr/local/opt/llvm/bin/clang++
      - name: Run tests
        run: |
          bazel test --config=py --python_version=${{ matrix.python_version }} ${{ env.LUCID_FLAGS }} //tests/bindings/pylucid/...

  build:
    runs-on: ubuntu-22.04
    # needs: test # TODO: enable this again
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          # - macos-latest
          # - windows-latest
        python_version:
          - "3.8"
          # - "3.9"
          # - "3.10"
          # - "3.11"
          # - "3.12"
          # - "3.13"

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/gurobi-lib
        id: gurobi-lib
        with:
          os: ${{ matrix.os }}
          version: "12.0.0"
      - uses: ./.github/actions/bazel-cache
      - uses: ./.github/actions/frontend-setup
        if: matrix.os == 'windows-latest'

      # - name: Install openmp on macOS
      #   if: matrix.os == 'macos-latest'
      #   run: |
      #     brew install llvm libomp
      #     export CC=/usr/local/opt/llvm/bin/clang
      #     export CXX=/usr/local/opt/llvm/bin/clang++

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python_version }}"
          cache: "pip"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools wheel twine

      - name: Build a binary wheel and a source tarball
        run: python3 -m build
        env:
          GUROBI_HOME: ${{ steps.gurobi-lib.outputs.gurobi-home }}
          LD_LIBRARY_PATH: ${{ steps.gurobi-lib.outputs.gurobi-home }}/lib

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-${{ matrix.os }}-${{ matrix.python_version }}
          path: dist/

  publish:
    # if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          path: dist/
          merge-multiple: true

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          verbose: true
          repository-url: https://gitlab.com/api/v4/projects/71977529/packages/pypi
          user: pylucid
          attestations: false
          password: ${{ secrets.GITLAB_PACKAGE_TOKEN }}
